[package]
name = "ink-fs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ink-core = { path = "../ink-core" }
serde.workspace = true
toml.workspace = true

[dev-dependencies]
tempfile = "3.23.0"
